#HTTP_Listener_config

#HTTP_Listener_config

http:
  host: "localhost"
  port: "8081"
  timeout: "30000"

#MySQL Database

db:
  mysql:
    host: "localhost"
    port: "3306"
    username: "DB"
    password: "![DVEHPlNnkQqnk6GEH5QsyyiXnNOJJ6zYFxn+0fP+X+Y=]"
  elephantdb:
    url: "jdbc:postgresql://rain.db.elephantsql.com:5432/cogaowsy"
    driverclassname: "org.postgresql.Driver"
    username: "cogaowsy"
    password: "![TaW4JIjEgV3553birMGptI7mD/Yq0pCF/nUg6Z9gtExm3qHUyOqOpryLG3tI85fuoNovsup+7v1nltqyQNlNiw==]"
 

queue:
    jms:
      username: "admin"
      password: "![UIaBKO9QcEqgFcTbX1Hwb1i0YJl5OuMqWDgv7i1YHVY=]"
      brokerurl: " tcp://localhost:61616"
    
    
